name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: npm ci, build, test
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*" 
      - run: yarn ci
      - run: yarn run build --if-present
      - run: yarn test
