name: CI Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*" 
          cache: "yarn"

      - name: Run tests
        run: |
          yarn
          yarn test
